@urlDev=http://localhost:3051

### checkStatus
GET {{urlDev}}/checkstatus

###
POST {{urlDev}}/v1/services/users
Content-Type: application/json

{
  "username": "chris",
  "email": "chris.nguyen@lfglobaltech.com"
}